# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs:
- job: scan

  steps:
  - task: Docker@1
    displayName: Build Docker image for PR
    inputs:      
      command: "Build an Image"
      dockerFile: "$(Build.SourcesDirectory)/Dockerfile"
      imageName:  'sample'
  - script: |
      curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.32.1
      trivy -v      
  - task: CmdLine@2
    displayName: "Run trivy scan"
    inputs:
      script: |
        trivy image sample:latest
  - task: CmdLine@2
    inputs:
      script: 'docker images'     
  - task: trivy@1
    inputs:
      version: 'latest'
      docker: false
      image: "sample"
  
 
    
