# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs:
- job: scan
  steps:
  
  - task: Docker@1    
    displayName: Build Docker image for PR
    inputs:      
      command: "Build an Image"
      dockerFile: "$(Build.SourcesDirectory)/Dockerfile"
      imageName:  'sample'   
  - task: trivy@1   
    inputs:
      exitCode: 0
      docker: false
      devMode: true
      debug: true
      image: "sample:latest"
  
  - task: TrivyReporter@2
    inputs:    
      reportServerEndpoint: 'trivy-reporter'
      scannerResultsFile: 'default'

  
  # - script: |
  #      curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin v0.32.1
  #      trivy -v
  #   displayName: 'Download and install Trivy'
  # - task: CmdLine@2
  #   inputs:
  #     script: |
  #       trivy image --security-checks vuln,config,secret -f json -o results.json vulnerables/web-dvwa
  
  - task: CmdLine@2
    inputs:
      script: |        
        ls /tmp
        cp /tmp/trivy*.json $(Build.ArtifactStagingDirectory) 
        echo "$(Agent.WorkFolder)"
        echo "$(Agent.TempDirectory)"
  
  - task: CopyFiles@2
    inputs:
      contents: '/tmp/trivy/*.*'
      targetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      artifactName: MyBuildOutputs
  
 
    
