# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs:
- job: scan
  steps:
  - task: Docker@1    
    displayName: Build Docker image for PR
    inputs:      
      command: "Build an Image"
      dockerFile: "$(Build.SourcesDirectory)/Dockerfile"
      imageName:  'sample'   
  # - task: trivy@1   
  #   inputs:
  #     version: 'v0.32.0'
  #     docker: false
  #     devMode: true
  #     image: "sample:latest"
  #     aquaKey: '4bwsbokT452XYMn0JKfjK0'
  #     aquaSecret: 'SPgT3W9Kyj7zE6FuibgswoF1NzD9I6TiTgb'
  
  - script: |
       curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin v0.32.1
       trivy -v
    displayName: 'Download and install Trivy'
  - task: CmdLine@2
    inputs:
      script: |
        trivy image -f json -o results.json golang:1.12-alpine
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Pipeline.Workspace)'
      artifact: '*.json'
      publishLocation: 'pipeline'
  
 
    
