on: [push]

jobs:
 build:
  name: Build
  runs-on: ubuntu-20.04
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Google OSV scanner
      uses: google/osv-scanner@main
      with:
          args: -r .
    - name: Build an image from Dockerfile
      run: |
         docker build -t docker.io/my-organization/my-app:${{ github.sha }} .
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
        format: 'json'
        output: 'trivy_results.json'

    - name: Upload Results     
      uses: kunal-deshmukh-deltatre/trivy-reporter-ts@v1.16
      with:
        endpointUrl: 'https://trivyscannerapi.azurewebsites.net/api/scanner-api-function'
        apiKey: ${{ secrets.API_KEY }}        
  


     
