on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
     - name: Build an image from Dockerfile
       run: |
          docker build -t docker.io/my-organization/my-app:${{ github.sha }} .
          
     - name: Run Trivy vulnerability scanner
       uses: aquasecurity/trivy-action@master
       with:
         image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
         format: 'json'
         output: 'trivy-results.json'
    
     - name: Upload Results
       id: hello
       uses: kunal-deshmukh-deltatre/trivy-reporter-ts@v1.0
       with:
        milliseconds: 1000
     
